name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: keth-jnsk
          outputs: |
            dist/github-snake.svg?palette=github-dark&color_snake=#ffb6c1
      - name: Commit & Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dist/
          git commit -m "Generate pink snake animation"
          git push
