name: Generator Snake
on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12h
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p dist
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake-pink.svg?palette=github-dark&color_snake=#ffb6c1
